### ISSUE TITLE
ctx.ExecutionContext struct has fields FeatureToggleID and ExperimentBucket

### ISSUE THREAD

**Issue by arberiii** [short-d/app#91]
https://github.com/short-d/app/blob/30e9580abb8bb2a711a22e043748cdd18f72fc8b/fw/ctx/execution.go#L13-L14 the ExecutionContext struct has fields FeatureToggleID and ExperimentBucket which seem quite arbitrary and are used in DataDog tags. I feel like those were added while developing for testing purposes and are related to short-d/short repository. What is the reason for having them?

**Comment by byliuyang** [comment]
Tracking for A/B testing
